/**
 * Generates supabase/seed.sql from the typed catalog & demo data in lib/data.
 * Usage: npm run seed:generate
 */
import { writeFileSync } from "node:fs";
import { createHash } from "node:crypto";
import { CATEGORIES, CITIES, SERVICE_TYPES, DEFAULT_PLANS } from "../lib/data/catalog";
import { PROVIDERS } from "../lib/data/providers";
import { SEED_PROMOS } from "../lib/data/seed";

const q = (v: unknown) => (v === null || v === undefined ? "null" : typeof v === "number" || typeof v === "boolean" ? String(v) : `'${String(v).replace(/'/g, "''")}'`);
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;
const uuid = (s: string) => { const h = createHash("md5").update(s).digest("hex"); return `${h.slice(0, 8)}-${h.slice(8, 12)}-4${h.slice(13, 16)}-a${h.slice(17, 20)}-${h.slice(20, 32)}`; };
const commission = { free: 15, pro: 10, business: 8, premium: 5 } as const;
const out: string[] = ["-- generated by scripts/generate-seed.ts — do not edit by hand", "begin;"];

out.push(`insert into public.cities (slug, name, region, lat, lng, sort) values\n${CITIES.map((c, i) => `(${q(c.slug)}, ${j(c.name)}, ${j(c.region)}, ${c.lat}, ${c.lng}, ${i})`).join(",\n")}\non conflict (slug) do nothing;`);
out.push(`insert into public.categories (id, slug, icon, name, description, sort) values\n${CATEGORIES.map((c, i) => `(${q(c.id)}, ${q(c.slug)}, ${q(c.icon)}, ${j(c.name)}, ${j(c.description)}, ${i})`).join(",\n")}\non conflict (id) do nothing;`);
out.push(`insert into public.service_types (slug, category_id, name, query, from_price) values\n${SERVICE_TYPES.map((s) => `(${q(s.slug)}, ${q(s.categoryId)}, ${j(s.name)}, ${j(s.query)}, ${s.fromPrice})`).join(",\n")}\non conflict (slug) do nothing;`);
out.push(`insert into public.plans (id, price_usd, commission_percent, features, is_highlighted) values\n${DEFAULT_PLANS.map((p) => `(${q(p.id)}, ${p.priceUsd}, ${commission[p.id]}, ${j(p.features)}, ${!!p.highlighted})`).join(",\n")}\non conflict (id) do nothing;`);
out.push(`insert into public.platform_settings (key, value) values ('service_fee', '{"percent": 5}'), ('payout_day', '{"weekday": 1}') on conflict (key) do nothing;`);
out.push(`insert into public.promo_codes (code, percent, max_uses, uses, is_active, expires_at) values\n${SEED_PROMOS.map((p) => `(${q(p.code)}, ${p.percent}, ${p.maxUses}, ${p.uses}, ${p.active}, ${q(p.expiresAt)})`).join(",\n")}\non conflict (code) do nothing;`);

// demo specialists (auth user → public.users via trigger → provider)
for (const p of PROVIDERS) {
  const uid = uuid(`user:${p.id}`), pid = uuid(`provider:${p.id}`);
  out.push(`insert into auth.users (id, email, raw_user_meta_data, aud, role, created_at) values (${q(uid)}, ${q(`${p.id}@demo.ustago.uz`)}, ${j({ full_name: p.name, phone: p.phone })}, 'authenticated', 'authenticated', now()) on conflict (id) do nothing;`);
  out.push(`update public.users set role = 'provider', city_slug = ${q(p.citySlug)}, avatar_url = ${q(p.avatar)} where id = ${q(uid)};`);
  out.push(`insert into public.providers (id, user_id, slug, display_name, profession, category_id, city_slug, district, lat, lng, about, price_from, price_unit, response_minutes, experience_years, languages, phone, is_verified, badges, plan, status, rating, reviews_count, orders_count, weekly_hours) values (${q(pid)}, ${q(uid)}, ${q(p.id)}, ${q(p.name)}, ${j(p.profession)}, ${q(p.categoryId)}, ${q(p.citySlug)}, ${q(p.district)}, ${p.lat}, ${p.lng}, ${j(p.about)}, ${p.priceFrom}, ${q(p.priceUnit)}, ${p.responseMinutes}, ${p.experienceYears}, array[${p.languages.map(q).join(",")}], ${q(p.phone)}, ${p.verified}, array[${p.badges.map(q).join(",")}]::text[], ${q(p.plan)}, 'active', ${p.rating}, ${p.reviewsCount}, ${p.ordersCount}, ${j(p.availability)}) on conflict (id) do nothing;`);
  if (p.serviceSlugs.length) out.push(`insert into public.provider_service_types (provider_id, service_type_slug) values ${p.serviceSlugs.map((s) => `(${q(pid)}, ${q(s)})`).join(", ")} on conflict do nothing;`);
  out.push(`insert into public.services (provider_id, name, price, unit, duration_min, sort) values ${p.services.map((s, i) => `(${q(pid)}, ${j(s.name)}, ${s.price}, ${q(s.unit)}, ${s.durationMin}, ${i})`).join(", ")};`);
  out.push(`insert into public.provider_portfolio (provider_id, title, image_path, completed_at, sort) values ${p.portfolio.map((x, i) => `(${q(pid)}, ${j(x.title)}, ${q(x.image)}, ${q(x.completedAt.slice(0, 10))}, ${i})`).join(", ")};`);
  const av = Object.entries(p.availability).filter(([, h]) => h).map(([d, h]) => `(${q(pid)}, ${d}, '${String(h![0]).padStart(2, "0")}:00', '${String(h![1]).padStart(2, "0")}:00')`);
  if (av.length) out.push(`insert into public.provider_availability (provider_id, weekday, start_time, end_time) values ${av.join(", ")} on conflict do nothing;`);
}
out.push("commit;");
writeFileSync("supabase/seed.sql", out.join("\n\n") + "\n");
console.log(`seed.sql: ${PROVIDERS.length} providers, ${SERVICE_TYPES.length} service types, ${CITIES.length} cities`);
